######################################################################
# Automatically generated by qmake (3.0) Sat Jan 7 01:40:57 2017
######################################################################

TEMPLATE = app
TARGET = Qt
INCLUDEPATH += .
QT += widgets
LIBS += -lalut -lopenal
# Input
HEADERS += speaker_detect.h
SOURCES += GUI.cpp main.cpp train_test.cpp record.cpp
